### ISSUE TITLE
Use image title as alt text

### ISSUE THREAD

**Issue by moritzebeling** [encoding-group/svelte-website#12]

**Comment by reneweiser** [comment]
Wordpress generates media titles from the media filename, which can include the file extension. Those are not good alt texts. A better solution would be to use the built in alt field.

Edit: Although the alt field needs to be populated manually.

**Comment by moritzebeling** [comment]
Ich dachte man nimmt den title und nicht den alt text deswegen, weil man hier eine gute Übersicht über die titles hat und dann das serielle bearbeiten einfacher, bzw übersichtlicher ist.

<img width="1046" alt="Bildschirmfoto 2020-09-09 um 13 10 58" src="https://user-images.githubusercontent.com/39742729/92591284-e987cd80-f29d-11ea-873e-4424a05c7fe5.png">

Edit: Das Alt-Feld ist halt immer weiter unten und mehr versteckt deshalb nicht so einfach zu erreichen

**Comment by moritzebeling** [comment]
Durch die API sollte es ja wahrscheinlich egal sein, welches Feld man jetzt nutzt. Noch dazu ist doch der Filename ein gutes fallback. besser als ein leeres Alt-Feld
