### ISSUE TITLE
Don't show discipline 'Uncategorized'

### ISSUE THREAD

**Issue by moritzebeling** [encoding-group/svelte-website#27]
Es ist scheinbar nicht möglich für einen Post **keine** Kategorie zu haben. Es stellt dann immer wieder auf Uncategorized. Es wäre dann gut, die auszuschließen sodass das im Frontend nicht angezeigt wird.

**Comment by reneweiser** [comment]
Den kompletten Post rausfiltern oder nur die Kategorie dann nich anzeigen?

**Comment by moritzebeling** [comment]
Nur die Kategorie nicht anzeigen. Also
```
discipline: ['Uncategorized']
```
wird zu
```
discipline: []
```
Ich stell das dann so dar:
```
Client: {post. discipline.length > 0 ? post. discipline.join(', ') : '—'}
```
