### ISSUE TITLE
Wordpress improvement suggestions

### ISSUE THREAD

**Issue by moritzebeling** [encoding-group/svelte-website#3]
I just logged in to wordpress to edit some content, and have a few ideas for de-cluttering :)

# Posts
- do we need the key/value pairs here?
- instead of using a custom field for `year`, can’t we just use the wp build in date field?
- instead of using a custom field for `title image`, wouldn’t it make sense to use the wp build in feature for title image?

**Comment by reneweiser** [comment]
Key/value pairs are not needed and can be removed.

We can use the built in fields for year and title image. My rationale was to have all the fields in one place without having to think about which ones were built in and which ones weren't.

**Comment by moritzebeling** [comment]
okay. I think for the title image it does make sense, because it is fairly hidden in the side bar.

For the date, I would consider using the build in field, because posts are ordered chronological by that field.

**Comment by reneweiser** [comment]
As I understood it, it is possible for the year of the project to be different from the created_at field of the post.

Posts can be sorted by any parameter.

**Comment by moritzebeling** [comment]
bin ja schon ruhig!
