### ISSUE TITLE
Add "project info" custom text field and display in left column

### ISSUE THREAD

**Issue by moritzebeling** [encoding-group/svelte-website#36]
For additional project info like:

Posters: DIN A1, 4c Offset-Print
Wall design: 3000x2000mm, 4c Digital-Print on adhesive film

**Comment by moritzebeling** [comment]
Platzhalter eingefügt https://github.com/encoding-group/robinweissenborn.de/commit/0fe4b867565826c438887933bfc00767e487121f

**Comment by reneweiser** [comment]
Should this be a repeater field where you can add as many fields as you like, with custom labels? I'd imagine that its not always "Posters" and "Wall design".

**Comment by moritzebeling** [comment]
@reneweiser `textarea`

**Comment by moritzebeling** [comment]
Aber es sollten mindestens Zeilenumbrüche möglich sein, vielleicht auch kursiv und Links oder so.

**Comment by moritzebeling** [comment]
@robinweissenborn

**Comment by moritzebeling** [comment]
`textarea` -> `wysiwyg`
