### ISSUE TITLE
Better image quality in frontend

### ISSUE THREAD

**Issue by moritzebeling** [encoding-group/svelte-website#37]

**Comment by moritzebeling** [comment]
@robinweissenborn ist die Bildqualität immer noch mies? oder schon besser?

**Comment by robinweissenborn** [comment]
Hehe, kann ich grad nicht nachschauen, weil der Bild-Slider grad nicht funktioniert. 
War ja bei Das Bauhaus Dalla Turingia besonders aufgefallen.

**Comment by moritzebeling** [comment]
<img width="1323" alt="Bildschirmfoto 2020-09-10 um 12 44 29" src="https://user-images.githubusercontent.com/39742729/92719415-603ace80-f363-11ea-8214-24ba0a3e6c82.png">
Im responsive view scheint bei einer Bildschirmbreite von 320 und 375 das Bild extrem unscharf zu sein. Ab 414 ist es dann gestochen scharf.

Da müsste man wohl das srcset anpassen, oder?

**Comment by robinweissenborn** [comment]
Also aufm Desktop ist jetzt alles tutti! 
Aufm Smartphone wäre natürlich auch schön wenn es scharf wäre :-)
