### ISSUE TITLE
Video-Links don't work

### ISSUE THREAD

**Issue by robinweissenborn** [encoding-group/svelte-website#38]
If a Video-URL is added in the Backend, it doesn't show up in Frontend. Instead its just an empty frame.
(see Horizonte, Animations)

**Comment by reneweiser** [comment]
Its not a bug, we haven't built video embedding yet.

**Comment by robinweissenborn** [comment]
Hey René! No problemo! Its not super high-priority...
But I can still fill in the links and later they will work? If you embedded the functionality for videos?

**Comment by reneweiser** [comment]
Hey Robin,
I'm not sure yet. It is possible you will need to use the embed snipped from the vimeo share function. It's the little paper plane icon in the video overlay when you watch the video on the vimeo website. Here is an example:

```
<iframe src="https://player.vimeo.com/video/453206040" width="640" height="360" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>
<p><a href="https://vimeo.com/453206040">Arrhov Frick Teaser, Horizonte</a> from <a href="https://vimeo.com/user16971508">robin</a> on <a href="https://vimeo.com">Vimeo</a>.</p>
```

On the other hand it should be possible to build this snippet in code from the links you already provided. I want to test this before I give a final answer.

**Comment by reneweiser** [comment]
@robinweissenborn Do you want to embed from vimeo only or do you need this to work for other video streaming services?

**Comment by robinweissenborn** [comment]
I also have videos from YouTube wich I want to link/embedd. For example:
https://www.youtube.com/watch?v=mceyHk8bDBQ
