### ISSUE TITLE
Archive Overview is limited to 10 posts?

### ISSUE THREAD

**Issue by robinweissenborn** [encoding-group/svelte-website#45]
The left side of the archive contains out of images – is this limited to 10? 
Is it possible to raise it up? It would be cool to have a little preview image for all projects. :)

**Comment by reneweiser** [comment]
Thats an easy fix. 10 is just the default.

**Comment by robinweissenborn** [comment]
Cool! There 20 projects until the launch of the site. More to come, but not more than 30 or maybe 40...
