### ISSUE TITLE
When on info page, link to home page

### ISSUE THREAD

**Issue by moritzebeling** [encoding-group/svelte-website#5]
The "Robin Weißenborn" Link in the upper left corner should link to `/info`. But when you’re on the info page, it should link to the index page `/`:

https://github.com/encoding-group/robinweissenborn.de/blob/0c0f55371a6ed5590ee314327cce1df933966754/src/pages/_components/Navigation.svelte#L30

**Comment by reneweiser** [comment]
Resolved by 11f2ada95821cdeaa9ff5e1bcd05cc9b35ab39b9
