### ISSUE TITLE
generate sitemap.xml

### ISSUE THREAD

**Issue by moritzebeling** [encoding-group/svelte-website#53]
Ansätze:
- Die Sitemap wird auf dem Wordpress-Server generiert, das Frontend referenziert diese
- Die Sitemap wird auf dem Wordpress-Server generiert, das Frontend lädt diese und gibt sie wieder
- Es gibt eine eigenen API-Endpoint, die alle Sitemap-Relevanten Infos zurückgibt, woraus im Frontend die Sitemap generiert wird
- Die Sitemap wird im Frontend generiert, aus den Daten der Posts-List, und ggf mit hardcoded Elementen ergänzt

**Comment by moritzebeling** [comment]
Sitemaps Protocol
https://www.sitemaps.org/protocol.html

Sitemap Images
https://support.google.com/webmasters/answer/178636

Sitemaps done in Sapper
https://www.reddit.com/r/sveltejs/comments/hrwojw/is_there_a_way_to_generate_sitemaps_for_a_sapper/
https://github.com/doppelganger9/blog/blob/master/src/routes/sitemap.xml.js

**Comment by moritzebeling** [comment]
- `/`
- `/info`
- `/imprint`
- `/archive`
- `/archive/...`
- `/archive/.../image....jpg`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
  <!-- index -->
  <url>
    <loc>https://robinweissenborn.de</loc>
    <changefreq>monthly</changefreq>
    <priority>0.5</priority>
  </url>
  <!-- info -->
  <url>
    <loc>https://robinweissenborn.de/info</loc>
    <changefreq>monthly</changefreq>
    <priority>0.5</priority>
  </url>
  <!-- imprint -->
  <url>
    <loc>https://robinweissenborn.de/imprint</loc>
    <changefreq>yearly</changefreq>
    <priority>0</priority>
  </url>
  <!-- archive -->
  <url>
    <loc>https://robinweissenborn.de/archive</loc>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  <!-- loop projects -->
  <url>
    <loc>https://robinweissenborn.de/archive/...</loc>
    <changefreq>monthly</changefreq>
    <priority>1</priority>
    <!-- loop images -->
    <image:image>
      <image:loc>https://robinweissenborn.de/archive/.../image-1.jpg</image:loc>
      <image:title>Image title</image:title>
    </image:image>
  </url>
  ..
</urlset>
```

**Comment by moritzebeling** [comment]
route ist da. jetzt muss routify "nurnoch" wissen, dass das keine html Seite sondern xml ist...
und natürlich noch die echten Daten rein...

**Comment by moritzebeling** [comment]
Scheduled rebuilds with GitHub Actions:
https://medium.com/@wearethreebears/scheduling-jamstack-builds-in-netlify-with-github-actions-509fcc87fa72

**Comment by moritzebeling** [comment]
Frage bei Discord:
> Hi there, I am kinda new to routify and I was wondering how I would I create a sitemap.xml of all my routes? Can I set an XML header? I assume not. But what do I do instead?

Antwort:
> @moritz you might be able to use routes.js or urlIndex.json from the routifyDir
> if it's for runtime, you can also walk through the page tree using $layout

**Comment by reneweiser** [comment]
Das ist die Antwort auf "Wie bekomme ich eine Sammlung der Links zu allen Seiten" nicht "Wie liefere ich XML aus"

**Comment by moritzebeling** [comment]
Es gibt scheinbar ein Netlify Sitemap Plugin, dass bei Rebuilds eine Sitemap erstellt:
https://github.com/netlify-labs/netlify-plugin-sitemap
Die Frage ist, ob man da auch dynamische Seiten mit integrieren kann, denn es geht ja hauptsächlich um die Projekt-Seiten und deren Bilder...
Wenn man das irgendwie hinbekäme, beim Build eine vollständige sitemap zu generieren, könnte man das ja mit Auto-Rebuilds kombinieren und das zB ein mal im Monat neu generieren...

**Comment by reneweiser** [comment]
Habe das Plugin mal eingerichtet. Es wird nun eine [Sitemap generiert und aus geliefert](https://robinweissenborn.de/sitemap.xml). Allerdings sind gerade die wichtigen URLs (Projekte und deren Bilden) nicht enthalten. Leider gibt auch die Dokumentation wenig Aufschluss über eventuelle Einstellungen mit denen man diese mit einbeziehen könnte. Da das Plugin ein von Routify unabhängiges Projekt ist, kann ich mir auch kaum vorstellen, dass es möglich ist. [`makeSitemap`](https://github.com/netlify-labs/netlify-plugin-sitemap/blob/df8438dce6795a38b7f6b8c8e93729c5903f6a86/make_sitemap.js#L8) schaut sich nur die statischen Seiten an die im `dist`-Ordner liegen.

**Comment by moritzebeling** [comment]
Cool, dass ist doch schonmal super!
Hab zumindest mal die `changefreq` auf `monthly` gesetzt https://github.com/encoding-group/robinweissenborn.de/commit/dfb9fa31c5fa07695f08a4eac7bb8e076e8b2a2a

Wenn man sich die `makeSitemap` Funktion anguckt, sieht man ja wie die das machen. In `urls` (line 17) scheinen dann alle statischen URLs drin zu sein. Müsste doch einfach sein, einfach eine Liste all unserer dynamischen Seiten zu ergänzen.

**Comment by reneweiser** [comment]
Ich habe versucht das Plugin um die Posts und deren Bilder zu erweitern, bin allerdings nicht weit gekommen.

Das plugin müsste noch etwas grundlegender umgeschrieben werden. Dh ich kann die dynamischen Inhalte nicht mal eben an einem Vormittag mit einbinden. Daher müsste ich es vorerst bei den statischen Seiten belassen. In den issues wird bereits nach SPA support gefragt. Evtl wird der Autor entsprechende Funktionalität nachliefern.

**Comment by moritzebeling** [comment]
Wäre das hier etwas? https://developer.aliyun.com/mirror/npm/package/rollup-plugin-sitemap

**Comment by reneweiser** [comment]
Habe in 4d8f1e35dd0dd3eeb0be620d5dd8a28898766911 und ff884eb55f2c1475c166531302a07321ee4e9c54 ein eigenes Rollup plugin eingebaut. Jetzt sind schonmal die Archivseiten mit dabei. Das plugin sollte allerdings flexibel genug sein, sodass man noch die Bilder mit dazu machen kann.

Versuch ich morgen mal.

**Comment by reneweiser** [comment]
Hab die Bilder doch noch jetzt hinzugefügt. Mit c69c6bb53adf6a76661c46f820120af56c88d27b sollte dieses issue erledigt sein.
