### ISSUE TITLE
Product Order-Link

### ISSUE THREAD

**Issue by moritzebeling** [encoding-group/svelte-website#54]
- Wie soll der Link heißen?
- An Robins normale email?
- Default Betreff/text in Mail?

**Comment by moritzebeling** [comment]
@robinweissenborn

**Comment by robinweissenborn** [comment]
Dear Robin,

I am interested in ordering some of your posters.
(A poster is 50€ plus shipping)
Could drop me a mail with all required information?

Your Name

Die Mail die sich aus dem Link generiert soll an die **info@robinweissenborn.de** gehen
Betreff: Horizonte posters

**Comment by robinweissenborn** [comment]
Dear Robin,

I am interested in ordering a Spotmap of Weimar.
(A Spotmap Weimar is 12€ plus shipping)
Could drop me a mail with all required information?

Your Name

Die Mail die sich aus dem Link generiert soll an die info@robinweissenborn.de gehen
Betreff: Spotmap Weimar

**Comment by moritzebeling** [comment]
**Link:** Order via E-Mail
**To:** info@...
**Subject:** Order inquiry for {{post.title}}
**Body:**

Dear Robin,

I am interested in ordering a {{post.title}} for {{post.price}} € + shipping cost.
Could you drop me a mail with all required information?

Thank you

**Comment by robinweissenborn** [comment]
»Could **you** drop me...«
Hatte ich aber falsch geschrieben...
Ansonsten top!

**Comment by robinweissenborn** [comment]
ATTENTION: The generated E-Mail is adressed to: info@robinweißenborn.de
Could you correct the ß to ss?
