### ISSUE TITLE
Show always secondary image on home page?

### ISSUE THREAD

**Issue by moritzebeling** [encoding-group/svelte-website#57]
Sollen wir auf der Startseite immer das 2. Bild anzeigen? solange es eines gibt?

**Comment by robinweissenborn** [comment]
Nope, bitte immer NUR das Erste. 
Das Zweite ist ja meistens ein gif was ich ziemlich klein halten muss von der Auflösung her, wäre also als Startenseitenbild viel zu klein. 
Geht das so?

**Comment by robinweissenborn** [comment]
Kurz nachgefragt: müsste das 2. Bild nicht auf der Archivseite angezeigt werden wenn ich über ein Bild hovere?

**Comment by moritzebeling** [comment]
Alles klar, ja dann ist es ja schon fertig
