### ISSUE TITLE
Update Custom Fields

### ISSUE THREAD

**Issue by moritzebeling** [encoding-group/svelte-website#6]
**Info page**
- Rename "General" to "Website Metadata"
- Wofür ist "Title"? Kann das weg?
- Rearrange Contact info like:
  - Contact (name, mail, tel)
  - Address 1 (street, zip, city, country)
  - Address 2 (street, zip, city, country)

**Post**
- Year datepicker nervt und produziert Fehler, stattdessen lieber ein number oder text feld mit `YYYY` als Platzhalter
- "Short title" kann weg

Führt möglicherweise dazu, dass API Adapter ebenfalls überarbeitet werden muss

**Comment by reneweiser** [comment]
Erledigt.
