### ISSUE TITLE
Startseite limited to 3 posts?

### ISSUE THREAD

**Issue by moritzebeling** [encoding-group/svelte-website#60]

**Comment by reneweiser** [comment]
Number of posts returned by the request is controlled by the query string on line 11 in `/src/pages/index.svelte`.

`fetch("https://api.robinweissenborn.de/wp-json/wp/v2/posts?per_page=5")` returns 5 posts which then get filtered down to 3. You can up [`per_page`](https://developer.wordpress.org/rest-api/using-the-rest-api/pagination/) to max 100.

**Comment by moritzebeling** [comment]
`posts?sticky=true`
