### ISSUE TITLE
Ideas for Wordpress speed up

### ISSUE THREAD

**Issue by moritzebeling** [encoding-group/svelte-website#65]
According to https://kinsta.com/de/lernen/wordpress-beschleunigen/ wo could try:

- Reducing the number of revisions, Wordpress remembers
```php
define( 'WP_POST_REVISIONS', 3 );
```

- allow Wordpress all the memory that is available:
```php
define( 'WP_MEMORY_LIMIT', '512M' );
```

- Asset caching in htaccess
```
<filesMatch ".(pdf|jpg|jpeg|png|gif|svg)$">
Header set Cache-Control "max-age=84600, public"

ExpiresActive On
ExpiresByType image/jpg "access 1 year"
ExpiresByType image/jpeg "access 1 year"
ExpiresByType image/gif "access 1 year"
ExpiresByType image/png "access 1 year"
ExpiresByType image/svg "access 1 year"
ExpiresByType application/pdf "access 1 month"
ExpiresDefault "access 1 month"
```

- gzip für die json api aktivieren

**Comment by moritzebeling** [comment]
+ das API cache plugin https://github.com/encoding-group/robinweissenborn.de/issues/7

**Comment by reneweiser** [comment]
Ich denke das Problem ist mit #7 gelöst. Bilder und andere Assets werden von Routify schon gecached:

> By default, components of a Routify starter template app are fully cached and available offline.
> External assets are automatically cached when requested.
[Source](https://routify.dev/wip/prefetch-and-cache)

**Comment by moritzebeling** [comment]
super. was ist mit revisions und memory?
Manche Seiten haben jetzt bereits mehr als 30 Revisionen.

**Comment by reneweiser** [comment]
Ich sehe jetzt erstmal keinen Bedarf für diese Änderungen.
