### ISSUE TITLE
Website is slow, manche Inhalte clientseitig im store speichern

### ISSUE THREAD

**Issue by moritzebeling** [encoding-group/svelte-website#67]
eigentlich hatten wir das schonmal https://github.com/encoding-group/robinweissenborn.de/issues/15, aber irgendwie ist es immer noch so, dass wenn man auf Archiv/Info/Start klickt laden die Inhalte, und später wenn man nochmal hin klickt laden sie schon wieder. Wäre es nicht schlau, die Seiten, auf die man immer wieder geht in einem Store zu speichern?

```js
// pseudo code

let archiveStore = false;
function getArchiveData(){
  if(archiveStore === false){
    archiveStore = fetch(...);
  }
  return archiveStore;
}
```

Naja, das ist natürlich nur hingekritzelt, aber irgendwie müsste es halt so sein, dass die infos nur beim ersten mal geladen werden.

Allerdings nur bei den folgenden Seiten (Alle anderen Seiten besucht man ja wahrscheinlich nur 1 mal)
- archive (list of all posts)
- info

Um nicht noch eine zusätzliche Anfrage zu haben, kann man für die Start-Seite dann doch wieder die gesamte Liste filtern

Vielleicht kann man, diesen Fetch dann auch schon vorladen. Wenn man also, zB auf einer einzelnen Projekt-seite zuerst ankommt, dass man dann, nach einem kleinen Timeout, die info-Seite und die Archiv-Liste schonmal lädt. dann geht das zack zack

**Comment by reneweiser** [comment]
Den Sessionstore cache habe ich mit dem WordpressAdapter entfernt und wollte statt dessen Routify's prefetching feature nutzen.

Schau mal hier: https://routify.dev/guide/prefetching

**Comment by moritzebeling** [comment]
Sieht cool aus

**Comment by reneweiser** [comment]
Da API responses jetzt gecached werden #7 könnte man überlegen ob das Problem "holprig" nicht damit schon gelöst ist?
