### ISSUE TITLE
Metadata Error

### ISSUE THREAD

**Issue by moritzebeling** [encoding-group/svelte-website#68]
Console:
```
// getOrigin, helpers.js:466
Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'c(e).path')
```

Html:
```html
<script type="application/ld+json" ✂prettier:content✂="JyArIGpzb25sZCArICc=">{}</script>
<script type="application/ld+json" ✂prettier:content✂="JyArIGpzb25sZCArICc=">{}</script>
<meta name="author" content="undefined" data-origin="routify">
<meta property="og:author" content="undefined" data-origin="routify">
```

**Comment by moritzebeling** [comment]
https://github.com/encoding-group/robinweissenborn.de/issues/64

**Comment by reneweiser** [comment]
~~`<script type="application/ld+json" ✂prettier:content✂="JyArIGpzb25sZCArICc=">{}</script>` ist ein Autoformatter Problem. Easy fix kommt asap.~~

```html
<meta name="author" content="undefined" data-origin="routify">
<meta property="og:author" content="undefined" data-origin="routify">
```
Kann ich nicht reproduzieren. Mein Output:
```html
<script type="application/ld+json" ✂prettier:content✂="JyArIGpzb25sZCArICc=">{}</script>
<meta name="title" content="Robin Weißenborn" data-origin="routify">
<meta property="og:title" content="Robin Weißenborn" data-origin="routify">
<title>Robin Weißenborn</title>
<meta name="author" content="Robin Weißenborn" data-origin="routify">
<meta property="og:author" content="Robin Weißenborn" data-origin="routify">
<meta name="description" content="Robin Weißenborn Portfolio" data-origin="routify">
<meta property="og:description" content="Robin Weißenborn Portfolio" data-origin="routify">
<meta name="keywords" content="graphic, design, animation, 3d, rendering, artist, designer, leipzig, germany" data-origin="routify">
<meta property="og:keywords" content="graphic, design, animation, 3d, rendering, artist, designer, leipzig, germany" data-origin="routify">
<meta name="generator" content="encoding.group" data-origin="routify">
<meta property="og:generator" content="encoding.group" data-origin="routify">
<meta name="geo.region" content="DE" data-origin="routify">
<meta property="og:geo.region" content="DE" data-origin="routify">
<meta property="og:type" content="website" data-origin="routify">
<meta property="og:url" content="https://robinweissenborn.de" data-origin="routify">
<meta property="og:image" content="false" data-origin="routify">
<meta property="og:locale" content="de_DE" data-origin="routify">
```

**Comment by reneweiser** [comment]
9ee6d02c5999ccacadbb532a03e2b1072344a4fa fixed prettier autoformatting issue

**Comment by moritzebeling** [comment]
Also bei mir lokal habe ich:
- keinen Fehler in der Konsole
- ist das Autor Feld korrekt gefüllt
- und ist das jsonld dings nur ein mal, und zwar korrekt gefüllt.

Also alles gut. Aber live:
- gibt es diesen Konsolen-Fehler
- Ist das Autor Feld undefined
- und das jsonld ist doppelt, beim ersten mal richtig, beim zweiten mal undefined

**Comment by moritzebeling** [comment]
Es gab gerade eben einen moment, wo ich geschrieben hab:
```js
let author = 'Moritz';
metatags.author = author;
```
da ging es. keine Fehler.
Und jetzt, egal was ich probiere, bekomme ich immer einen Fehler (nicht lokal, nur bei netlify):
```js
let author = 'Robin Weißenborn';
metatags.author = author;
// or
metatags.author =  'Robin Weißenborn';
```

**Comment by moritzebeling** [comment]
jetzt sind plötzlich beide jsonLD undefined, obwohl ich daran nichts gemacht hab

**Comment by moritzebeling** [comment]
Und jetzt hab ich wieder den hier:
```
{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: Cannot read property 'getElementsByTagName' of undefined","trace":["Runtime.UnhandledPromiseRejection: TypeError: Cannot read property 'getElementsByTagName' of undefined","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:315:20)","    at processPromiseRejections (internal/process/promises.js:209:33)","    at processTicksAndRejections (internal/process/task_queues.js:98:32)"]}
```

Also irgendwie hab ich gerade das Gefühl, dass es eine 50/50 Sache ist, ob die Seite läuft oder nicht...

**Comment by moritzebeling** [comment]
Hab die Seite grad ca 50 mal neu geladen und es war sehr zuverlässig, immer abwechselnd einmal broken und einmal normal (1-2 ausnahmen, wo 2 mal hintereinander dasselbe kam)

**Comment by reneweiser** [comment]
Wow, the spam :D

Das Problem mit dem doppelten script tag [ist bekannt](https://github.com/sveltejs/svelte/issues/4982). Laut [diesem Issue](https://github.com/sveltejs/sapper/issues/1124) soll es helfen das script in einen `{@html}`-Block zu packen. In unserem Fall macht es offensichtlich keinen Unterschied. Insofern würde ich das als Framework Bug abhaken. Solange es keine negativen Auswirkungen auf SEO hat können wir es erstmal so stehen lassen.

Was die anderen Metatags betrifft könnte [dieses kleine Issue zum title tag](https://github.com/roxiness/routify/issues/253) vielleicht weiter helfen. Bei mir tritt das Problem wie gesagt nicht auf, daher kann ich es jetzt auch schlecht lösen.
