### ISSUE TITLE
Imprint Site is not editable by robin

### ISSUE THREAD

**Issue by robinweissenborn** [encoding-group/svelte-website#75]

**Comment by robinweissenborn** [comment]
https://www.dropbox.com/s/44a6ue4u7cuh3vs/Screencast-Imprint.mp4?dl=0

**Comment by moritzebeling** [comment]
Force https?
https://s0hungry.com/2020/06/28/real/

**Comment by moritzebeling** [comment]
> Force https?

Scheint eh schon gelöst zu sein

**Comment by reneweiser** [comment]
<img width="782" alt="Screenshot 2020-09-25 130617" src="https://user-images.githubusercontent.com/7584515/94260244-1a1f6680-ff30-11ea-958a-3d992b618dd0.png">

Diese Felder müssen die gleiche Basis URL habe weil das Wordpress Dashboard beim speichern von Pages die "Website-Adresse" nutzt um API Anfragen ans Backend zu machen. Wenn diese beiden Basis URLs verschieden sind kommt es zu [CORS errors](https://developer.mozilla.org/de/docs/Web/HTTP/CORS/Errors). Warum das Problem jetzt nur bei Imprint auftritt habe ich jetzt nicht weiter untersucht.

Habe nun die Website-Adresse jetzt auch als Subdomain `api` angegeben. Damit sollte das Problem gelöst sein.
