### ISSUE TITLE
OPTIONAL: Icons and Navigation elements

### ISSUE THREAD

**Issue by robinweissenborn** [encoding-group/svelte-website#76]
In case there is some time left :-P

Find a Favicon, arrows for the slideshows and a loading animation under the following link:
https://www.dropbox.com/s/ml9yxwjnk7izqvf/Icons-und-Steuerlemente.zip?dl=0

Im sure for the animated stuff you'll need an animated svg right?!
If that's the case, I'll find out how to do that.

**Comment by moritzebeling** [comment]
Also ich glaub die L-O-A-D-I-N-G Anim ist nice oder? Ich würd die nehmen, aber das wär dann gif. Den Kreis könnte ich ansonsten als animiertes Svg machen, so wie die Uhr

**Comment by moritzebeling** [comment]
Hab die Pfeile die jetzt mal unten in die ecken recht und links gemacht. und von der Größe passend zum Text. Was denkst du?

**Comment by robinweissenborn** [comment]
– LOADING hakt irgendwie zu sehr – lass lieber den Kreis nehmen. Cool? Wie brauchst du den?
– Die Pfeile waren eigentlich für den Mauszeiger gedacht :-D also wenn man über die Bilder eines Projekt hovert und dann der Pfeil nach links oder rechts kommt. (garnicht als Element auf der Seite sondern quasi statt dem Default Pfeil der Maus) 
Aber du meintest auch dass das evtl. zu aufwendig ist? Dann gerne auch weglassen.
– Das Favicon sieht irgendwie nicht gut aus, muss ich nochmal austauschen, die Strichstärken sind zu ähnlich und das schwarz müsste auch randabfallend sein.

**Comment by moritzebeling** [comment]
@robinweissenborn Soll der Schwarze Hintergrund bei den Maus-Cursor-Pfeilen mit drauf? Oder nur die weiße Linie auf transparent?

**Comment by robinweissenborn** [comment]
Nope, nur die weißen Pfeile – ohne Hintergrund.
