### ISSUE TITLE
Switch post taxonomies

### ISSUE THREAD

**Issue by moritzebeling** [encoding-group/svelte-website#8]
Derzeitige Verwendung:
- Kategorien (zum Häkchen setzen) für Kunden
- Schlagworte (Tag-List mit Autocomplete) für Disziplin

Wahrscheinlich wäre es schlauer, es genau anders herum zu haben: Disziplinen zum Anklicken und Kunden zum Eingeben

**Comment by reneweiser** [comment]
Erledigt.

**Comment by reneweiser** [comment]
Kategorien und Tags sind im Backend ausgetauscht.

**Comment by moritzebeling** [comment]
Muss auch noch fürs Frontend geändert werden, also wahrscheinlich bei Erstellung des Post-Objects *sorry*. Denn derzeit ist es vertauscht: https://github.com/encoding-group/robinweissenborn.de/issues/29
