### ISSUE TITLE
Klick on Project Name scrolls to Project info

### ISSUE THREAD

**Issue by robinweissenborn** [encoding-group/svelte-website#80]

**Comment by robinweissenborn** [comment]
Rename »Info« to »Project Info«

**Comment by moritzebeling** [comment]
https://github.com/cferdinandi/smooth-scroll

**Comment by moritzebeling** [comment]
das normale smooth scroll wird in safari leider nicht unterstützt.

**Comment by moritzebeling** [comment]
`scroll-behavior: smooth;`
Geht in alles Browsern, außer Safari
