### ISSUE TITLE
CORS Fehler

### ISSUE THREAD

**Issue by moritzebeling** [encoding-group/svelte-website#86]
Vllt brauchen wir auf dem Wordpress-Server folgenden Eintrag in der `.htaccess`:
```
<IfModule mod_headers.c>
  Header Set Access-Control-Allow-Origin "https://robinweissenborn.de"
  Header Set Access-Control-Allow-Origin "https://www.robinweissenborn.de"
  Header Set Access-Control-Allow-Origin "https://nostalgic-clarke-ad7627.netlify.app"
</IfModule>
```

**Comment by moritzebeling** [comment]
Auf nostalgic-clarke gibt es jetzt auch eine Reihe 404 Fehler. Ich weiß nicht (hoffe) dass das damit zu tun hat

**Comment by reneweiser** [comment]
Subdomain api.robinweissenborn.de hatte den falschen Dokumentstamm.
