### ISSUE TITLE
Layout und Spacing in Project page

### ISSUE THREAD

**Issue by moritzebeling** [encoding-group/svelte-website#88]
<img src="https://user-images.githubusercontent.com/39742729/95739624-6a662a80-0c8b-11eb-8a96-e673f2cace95.png" width="300" height="auto"/> <img src="https://user-images.githubusercontent.com/39742729/95739640-6f2ade80-0c8b-11eb-97f4-5e2c7554e225.png" width="300" height="auto"/>

**Variante 1:**
Oben links: Site title
Oben center: Project title
Oben rechts: Archive
Unten mittig: Gallery title, x/y
Project title weg

**Variante 2:**
Oben links Zeile 1: Site title
Oben links Zeile 2: Project title

**Comment by robinweissenborn** [comment]
Liebe Encoding Group,
wir machen es folgendermaßen:
Project page Aufbau **Variante 1**
Im Falle von mehreren Bildern kommt die Bildanzahl unter den Projektteil (Flyer UMBRUCH 1/2)
![Project-View-1](https://user-images.githubusercontent.com/70973644/95966056-f94d8100-0e0a-11eb-9299-6e813b319e84.jpg)
![Project-View-2](https://user-images.githubusercontent.com/70973644/95966066-fbafdb00-0e0a-11eb-9f3a-c7c7ff804edf.jpg)
