### ISSUE TITLE
undefined bug

### ISSUE THREAD

**Issue by robinweissenborn** [encoding-group/svelte-website#89]
Sometimes the Menu doesn't work, »undefined« appears in the browser tab. 
See Screencast: 
https://www.dropbox.com/s/sr69gmn3dyii5lf/201023-undefined-bug.mov?dl=0

**Comment by moritzebeling** [comment]
Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'j.length') `[postSlug].svelte`
